### ISSUE TITLE
Offline usage: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kpman** [jigsawye/swagit#11]
<img width="1419" alt="screenshot 2018-08-11 12 21 03" src="https://user-images.githubusercontent.com/2382594/43988132-825c2900-9d61-11e8-977b-d41d083004c1.png">

@jigsawye Do you have any idea about this situation?

**Comment by jigsawye** [comment]
Now that we’ve rewritten it in Rust, please reopen if this error still occurs.
